output_dir: ./emulators_separatedLHS/
trainingdata_csvfile_path:   ./trainingdata/separatedLHS_test.csv
validationdata_csvfile_path: ./trainingdata/separatedLHS_val.csv
testdata_csvfile_path:       ./trainingdata/separatedLHS_train.csv
feature_columns:
- sigma8
- Omegacdm
- w0
- wa
- log10fofr
- z
- log10k
label_columns:
- boost
batch_size:                  64
nthreads:                    32
hidden_layers:
- 16
- 8
learning_rate:               5.e-4
weight_decay:                5.e-6
activation_function:         'gelu'
loss_function:               'L1Loss'
max_epochs:                  1500
